# Generated by Django 3.0.7 on 2020-07-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_banks_branches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banks',
            options={'verbose_name': ['bank'], 'verbose_name_plural': 'banks'},
        ),
        migrations.AlterModelOptions(
            name='branches',
            options={'verbose_name': 'branch', 'verbose_name_plural': 'branches'},
        ),
    ]
